[package]
name = "rsdirstat-gui"
version = "0.1.0"
edition.workspace = true

[dependencies]
rsdirstat-core = { path = "../core" }
anyhow = "1"
axum = { version = "0.8", features = ["ws"] }
clap = { version = "4", features = ["derive"] }
mimalloc = "0.1"
open = "5"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time", "sync", "parking_lot"] }
tower-http = { version = "0.6", features = ["fs", "compression-gzip"] }

[target.'cfg(target_os = "macos")'.dependencies]
rsdirstat-macos = { path = "../macos" }

[target.'cfg(target_os = "linux")'.dependencies]
rsdirstat-linux = { path = "../linux" }

[target.'cfg(target_os = "windows")'.dependencies]
rsdirstat-windows = { path = "../windows" }
